[from-internal]
exten => 100,1,Answer()
 same => n,Wait(1)
 same => n,Playback(hello-world)
 same => n,Hangup()

[from-external]
exten => e,1,Goto(input)

exten => s,1,Answer()
 same => n,Wait(1)
 ; Prompt
 same => n(input),Read(input,nsw/listening&nsw/for&nsw/stop&nsw/or&nsw/platform&nsw/number&beep,0,t(#),5,5)
 same => n,Set(STOP_ID=${input})
 same => n(loop),NoOp()
 same => n,AGI(announcement.py,"${STOP_ID}")
 same => n,Wait(3)
 same => n,Goto(loop)
 same => n,Hangup()

exten => _.!,1,Goto(from-external,s,1)

[handle-input]
exten => e,1,Goto(error,s,1)
exten => _.!,1,Set(STOP_ID=${EXTEN})
 same => n(loop),NoOp()
 same => n,AGI(announcement.py,"${STOP_ID}")
 same => n,Wait(3)
 same => n,Goto(loop)

[error]
exten => s,1,NoOp()
 same => n,Wait(1)
 same => n,Playback(nsw/no&nsw/to&nsw/timetable&nsw/information&nsw/has-been-provided&nsw/by&nsw/Sydney&nsw/trains.f)
 same => n,Playback(nsw/Technicians-are-now-working-to-repair-the-problem&nsw/Thank-you)

[invalid_stop_id]
exten => s,1,NoOp()
 same => n,Wait(1)
 same => n,Playback(nsw/that&nsw/is&nsw/not&nsw/a&nsw/stop&nsw/or&nsw/platform&nsw/number)
 same => n,Goto(from-external,s,input)