[general]
dateformat=%F %T ; ISO 8601 date format
exec_after_rotate=rm ${filename}.2

[logfiles]
messages => security, notice, warning, error
security => security
console => security, notice, warning, error