[general]
localnet=127.0.0.1/32
localnet=172.16.0.0/255.252.0.0
context=from-external
transport=transport-udp
allowguest=yes
#exec echo "externhost=$(hostname -f)"
#exec echo "externip=$(LANG=c ip -c a s | grep -P "(?<=inet ).*(?=/32)" -o)"
nat=yes

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[system-tcp]
type=transport
protocol=tcp
bind=0.0.0.0

;===== TRUNK
[siptrunk]
type=registration
outbound_auth=siptrunk-auth
#exec echo "server_uri=sip:$(cat /run/secrets/sip_server)"
#exec echo "client_uri=sip:$(cat /run/secrets/sip_username)@$(cat /run/secrets/sip_server)"
retry_interval=60

[siptrunk-auth]
type=auth
auth_type=userpass
#exec echo "password=$(cat /run/secrets/sip_password)"
#exec echo "username=$(cat /run/secrets/sip_username)"

[siptrunk-aor]
type=aor
#exec echo "contact=sip:$(cat /run/secrets/sip_server):5060"

[siptrunk-endpoint]
type=endpoint
transport=transport-udp
context=from-external
disallow=all
allow=ulaw
outbound_auth=siptrunk-auth
aors=siptrunk-aor

[siptrunk-identify]
type=identify
endpoint=siptrunk-endpoint
#exec echo "match=$(cat /run/secrets/sip_match)"